import javax.swing.JOptionPane;
public class LoginForm extends javax.swing.JFrame {

    private DriverDatabase ddb=new DriverDatabase();
    private CustomerDatabase cdb=new CustomerDatabase();
    public LoginForm(CustomerDatabase cdb,DriverDatabase ddb) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.cdb=cdb;
        this.ddb=ddb;//to center it or to the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                         
    private void initComponents() {

       panel2 = new javax.swing.JPanel();
        userid = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        userid_text = new javax.swing.JTextField();
        password_text = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        signup = new javax.swing.JLabel();
        login_panel = new javax.swing.JPanel();
        login_header = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        panel2.setPreferredSize(new java.awt.Dimension(590, 413));

        userid.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userid.setText("UserID:");

        password.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        password.setText("Password:");

        userid_text.setBackground(new java.awt.Color(200, 212, 217));
        userid_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userid_textActionPerformed(evt);
            }
        });

        password_text.setBackground(new java.awt.Color(200, 212, 217));

        login_button.setBackground(new java.awt.Color(34, 137, 240));
        login_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_button.setText("LOGIN");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        signup.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("New User? Sign up now");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userid_text, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userid_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userid))
                .addGap(22, 22, 22)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password))
                .addGap(31, 31, 31)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        login_panel.setBackground(new java.awt.Color(0, 0, 0));
        login_panel.setPreferredSize(new java.awt.Dimension(615, 96));

        login_header.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        login_header.setForeground(new java.awt.Color(255, 255, 255));
        login_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_header.setText("LOGIN");
        login_header.setToolTipText("");

        javax.swing.GroupLayout login_panelLayout = new javax.swing.GroupLayout(login_panel);
        login_panel.setLayout(login_panelLayout);
        login_panelLayout.setHorizontalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(login_header)
                .addGap(230, 230, 230))
        );
        login_panelLayout.setVerticalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(login_header)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pack();
    }                      

    private void userid_textActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        DataBase conn = new DataBase();
        if(conn.login(userid_text.getText(),password_text.getText())==1)
        {
            if(cdb.isloggedin(userid_text.getText(), password_text.getText())==false)
            {
            Customer C=new Customer();
            cdb.LogIn(userid_text.getText(), password_text.getText(), C);
            this.setVisible(false);
            this.dispose();        
            profile p=new profile(C,ddb,cdb);
            p.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Already Logged in.");
            }
    
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please check your UserID or Password");
        }
        
    }                                            

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        RegisterForm rgf=new RegisterForm(cdb,ddb);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        this.dispose();
    }                                   


    // Variables declaration - do not modify                     
    private javax.swing.JButton login_button;
    private javax.swing.JLabel login_header;
    private javax.swing.JPanel login_panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JLabel signup;
    private javax.swing.JLabel userid;
    private javax.swing.JTextField userid_text;
    // End of variables declaration                   
}